Repository ParasX1/Financial-Investment-Tool, pull requests merged in 2025-08, with the labels that each got.

#98 Fixing portfolio
  client/components/StockCardComponent.tsx
  client/components/ohlc.tsx
  client/pages/dashboardView.tsx
  client/pages/index.tsx
Labels: bug, backend, Sprint4, frontend

#99 Add WatchlistPage front end with 3 chart and news rows and ticker-based news fetching (#83)
  client/components/NewsCardComponent.tsx
  client/components/StockCardComponent.tsx
  client/components/WatchlistCollapsibleCard.tsx
  client/pages/Watchlist.tsx
  client/services/news.ts
Labels: Sprint4, frontend

#100 Update Community.tsx
  .github/pull_request_template.md
  .github/workflows/python-app.yml
  README.md
  client/components/Footer.tsx
  client/components/StockCardComponent.tsx
  client/components/TextGrid.tsx
  client/components/navbar.tsx
  client/components/ohlc.tsx
  client/package-lock.json
  client/package.json
  client/pages/Community.tsx
  client/pages/Profile.tsx
  client/pages/dashboardView.tsx
  client/pages/index.tsx
  server/src/server.py
  server/src/stocks.py
  server/src/utils.py
  server/tests/api/test_user.py
  server/tests/test.py
  server/tests/test_stocks.py
Labels: Sprint5, frontend

#107 Metrics now get database data and connect with the backend
  client/components/StockCardComponent.tsx
  client/components/bargraph.tsx
  client/components/fetchMetrics.tsx
  client/components/graphSettingsModal.tsx
  client/components/linegraph.tsx
  client/components/scatterplot.tsx
  client/pages/dashboardView.tsx
  server/src/metrics.py
  server/src/server.py
Labels: backend, Sprint5, frontend, integration
